export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: {
          DEFAULT: 'var(--bg-primary)',
          card: 'var(--bg-card)',
          secondary: 'var(--bg-secondary)',
          muted: 'var(--text-muted)',
          tag: 'var(--tag-bg)',
        },
        accent: {
          DEFAULT: 'var(--accent-primary)',
          bg: 'var(--accent-bg)',
          secondary: 'var(--accent-secondary)',
          'secondary-bg': 'var(--accent-secondary-bg)',
          muted: 'var(--accent-hover)',
          bright: 'var(--accent-hover-bright)',
          tertiary: 'var(--tertiary)',
          'tertiary-container': 'var(--tertiary-container)',
          'tertiary-bg': 'var(--tertiary-bg)',
        },
        primary: {
          DEFAULT: 'var(--accent-primary)',
          hover: 'var(--accent-hover)',
        },
        border: 'var(--border-color)',
        error: {
          bg: 'var(--error-bg)',
          text: 'var(--error-text)',
        },
        success: {
          bg: 'var(--success-bg)',
          text: 'var(--success-text)',
        },
        star: {
          empty: 'var(--star-empty)',
          filled: 'var(--star-filled)',
          user: 'var(--star-user)',
        },
      },
      backgroundColor: {
        primary: 'var(--bg-primary)',
        accent: 'var(--accent-bg)',
        secondary: 'var(--bg-secondary)',
        card: 'var(--bg-card)',
        tertiary: 'var(--tertiary-bg)',
        'tertiary-container': 'var(--tertiary-container)',
        border: 'var(--border-color)',
        'accent-hover': 'var(--accent-hover)',
        'accent-secondary-bg': 'var(--accent-secondary-bg)',
        'surface-container-high': 'var(--skeleton-base)',
      },
      textColor: {
        primary: 'var(--text-primary)',
        secondary: 'var(--text-secondary)',
        muted: 'var(--text-muted)',
        error: 'var(--error-text)',
        accent: 'var(--accent-bg)',
        'accent-hover': 'var(--accent-hover)',
        'accent-secondary': 'var(--accent-secondary)',
        bright: 'var(--accent-hover-bright)',
        heart: 'var(--heart-color)',
        'heart-hover': 'var(--heart-hover)',
        button: 'var(--text-button)',
        tertiary: 'var(--tertiary)',
        'tertiary-container': 'var(--tertiary-container)',
      },
      borderColor: {
        DEFAULT: 'var(--border-color)',
        error: 'var(--error-text)',
        'bg-primary': 'var(--bg-primary)',
        'accent-primary': 'var(--accent-primary)',
        'accent-secondary': 'var(--accent-secondary)',
        'tertiary-container': 'var(--tertiary-container)',
      },
      boxShadow: {
        theme: '0 2px 4px var(--shadow-color)',
        'theme-lg': '0 4px 8px var(--shadow-color)',
        'primary-btn': '0 2px 4px var(--shadow-button)',
        'secondary-btn': '0 2px 4px var(--shadow-muted)',
      },
      fontFamily: {
        'headline': ['EB Garamond', 'serif'],
        'body': ['Work Sans', 'sans-serif'],
        'serif': ['EB Garamond', 'serif'],
        'sans': ['Work Sans', 'sans-serif'],
      },
      fontSize: {
        'headline-sm': ['24px', { lineHeight: '32px', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '40px', fontWeight: '500' }],
        'display-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'label-sm': ['12px', { lineHeight: '16px', fontWeight: '500' }],
      },
    },
  },
  plugins: [],
}